"""initial

Revision ID: 8aaa7b894aed
Revises: 
Create Date: 2026-05-11 06:42:12.758551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aaa7b894aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=False),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('headmaster_name', sa.String(length=150), nullable=True),
    sa.Column('headmaster_email', sa.String(length=120), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('province', sa.String(length=80), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key('fk_schools_created_by_id_users', 'schools', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_users_school_id_schools', 'users', 'schools', ['school_id'], ['id'])
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('guardian', sa.String(length=150), nullable=True),
    sa.Column('village', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('age_group', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('performance', sa.String(length=10), nullable=True),
    sa.Column('year_of_study', sa.String(length=20), nullable=True),
    sa.Column('social_activity', sa.String(length=20), nullable=True),
    sa.Column('lack_of_school_material', sa.Integer(), nullable=True),
    sa.Column('lack_of_school_fees', sa.Integer(), nullable=True),
    sa.Column('job_opportunity', sa.Integer(), nullable=True),
    sa.Column('pregnancy', sa.Integer(), nullable=True),
    sa.Column('family_conflicts', sa.Integer(), nullable=True),
    sa.Column('drug_abuse', sa.Integer(), nullable=True),
    sa.Column('lack_of_motivation', sa.Integer(), nullable=True),
    sa.Column('illness', sa.Integer(), nullable=True),
    sa.Column('absenteeism', sa.Integer(), nullable=True),
    sa.Column('bad_discipline', sa.Integer(), nullable=True),
    sa.Column('at_risk', sa.Boolean(), nullable=True),
    sa.Column('risk_probability', sa.Float(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_attendance_student_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_school_id_schools', 'users', type_='foreignkey')
    op.drop_constraint('fk_schools_created_by_id_users', 'schools', type_='foreignkey')
    op.drop_table('attendance')
    op.drop_table('students')
    op.drop_table('classes')
    op.drop_table('users')
    op.drop_table('schools')
    # ### end Alembic commands ###
